name: kasirfix
description: "Kasirfix kasir mobile app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0-beta.4
  google_fonts: ^6.3.2
  intl: ^0.20.2
  lucide_icons_flutter: ^3.0.6
  flutter_thermal_printer_plus: ^0.0.2
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

